server:
  port: 8084
  servlet:
    context-path: /resource1

spring:
  application:
    name: resource_client1

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
security:
  oauth2:
    client:
      clientId: client_1
      clientSecret: 123456
      userAuthorizationUri: http://localhost:8082/ptp-auth/oauth/authorize
      grant-type: code
      scope: all
      access-token-uri: http://localhost:8082/ptp-auth/oauth/token
    resource:
      token-info-uri: http://localhost:8082/ptp-auth/oauth/check_token
      prefer-token-info: true

