server:
  port: 8082
  servlet:
    context-path: /ptp-auth
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: ptp-auth
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/menhu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
security:
  oauth2:
    authorization:
      check-token-access: permitAll()
