server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  autoconfigure:
    # TODO: remove when fixed https://github.com/spring-projects/spring-security/issues/6314
    exclude: org.springframework.boot.actuate.autoconfigure.security.reactive.ReactiveManagementWebSecurityAutoConfiguration
    thymeleaf:
      cache: false
  application:
    name: gateway
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/menhu?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 123
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://client
          predicates:
            - Path=/client/**
          filters:
            - StripPrefix=0
            - TokenRelay=
  security:
    oauth2:
      client:
        registration:
          login-client:
            provider: ptp-auth
            client-id: client_1
            client-secret: 123456
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            redirect-uri-template: "{baseUrl}/login/oauth2/code/{registrationId}"
#            redirect-uri-template: "{baseUrl}/client"
            scope: all
        provider:
          ptp-auth:
#            authorization-uri: http://localhost:8090/uaa/oauth/authorize
#            token-uri: http://localhost:8090/uaa/oauth/token
#            user-info-uri: http://localhost:8090/uaa/userinfo
#            user-name-attribute: sub
#            jwk-set-uri: http://localhost:8090/uaa/token_keys
            authorization-uri: http://localhost:8082/ptp-auth/oauth/authorize
            token-uri: http://localhost:8082/ptp-auth/oauth/token
            user-info-uri: http://localhost:8082/ptp-auth/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8082/ptp-auth/token_keys

mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        #本地前端地址http://localhost:8000
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        allow-credentials: true
logging:
  level:
    root: debug

