server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: client
          uri: http://client
          predicates:
            - Path=/client/**

management:
  endpoints:
    web:
      exposure:
        include: '*'
  security:
    enabled: false

