server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: client
          uri: lb://client
          predicates:
            - Path=/client/**
#          filters:
#            - StripPrefix=0
management:
  endpoints:
    web:
      exposure:
        include: "*"
