server:
  port: 8081
  servlet:
    context-path: /

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
#      - http://localhost:8761/eureka/
spring:
  application:
    name: zuul
zuul:
  routes:
    api-1:
      stripPrefix: false
      path: /client/**
#      url: http://localhost:8083
      serviceId: CLIENT
    ptp-auth:
      stripPrefix: false
      path: /ptp-auth/**
      #      url: http://localhost:8083
      serviceId: ptp-auth


